# Generated by Django 3.0.7 on 2020-07-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMG_UPLOAD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
